### PR TITLE
Document pod placement options

### PR DESCRIPTION
**Pull request by tamalsaha**

### CODE REVIEW

**Comment by jipperinbham** [comment]
I was just trying out the `tolerations` but it doesn't appear to schedule the pods, any suggestions?

**Comment by tamalsaha** [comment]
@jipperinbham, can you please tell me about your setup? What does your Ingress look like? Does any node has matching taint?

**Comment by jipperinbham** [comment]
```yaml
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    app: app-ingress
  annotations:
    ingress.appscode.com/type: NodePort
    ingress.appscode.com/force-service-port: 'false'
spec:
  replicas: 2
  tolerations:
  - key: "RouterOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  tls:
  - secretName: app-cert
    hosts:
    - app.foobar.com
  rules:
  - host: app.foobar.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          - X-Forwarded-Proto https
```

```
$ kubectl describe node ip-X-X-X-X.ec2.internal | grep "[T]aints"
Taints:             RouterOnly=true:NoSchedule
```

the service gets created but the deployment doesn't seem to be getting created and I don't see anything in the voyager operator logs to indicate a failure.

**Comment by tamalsaha** [comment]
@jipperinbham , I tested this on GKE. I found one error in the docs and fixed it https://github.com/appscode/voyager/commit/b7d50a74f8caa47848e040bb43ff0ba6e1b91966

Otherwise it worked for me. Can you please delete the Ingress and try again?

**Comment by jipperinbham** [comment]
ok, I've narrowed down the issue a bit, I was able to create the ingress with only 1 host in the `rules` but if I added a second one it never creates the deployment, example ingress below:

```
spec:
  tolerations:
  - key: RouterOnly
    operator: Equal
    value: 'true'
    effect: NoSchedule
  tls:
  - secretName: app-cert
    hosts:
    - app.foobar.com
    - config.foobar.com
  rules:
  - host: app.foobar.com
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          - X-Forwarded-Proto https
- host: config.foobar.com
    http:
      paths:
      - backend:
          serviceName: config-web
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          - X-Forwarded-Proto https
```

**Comment by jipperinbham** [comment]
@tamalsaha just a quick update, I've tried various different Ingress objects and the theme seems to be if more than 1 item in an object is defined, it successfully gets all the services and endpoints but then never creates the ConfigMap or anything after that. In addition to the above spec that failed the one below also failed:

```yaml
  - host: config.foobar.com
    http:
      paths:
      - path: "/baz"
        backend:
          serviceName: baz-web
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          - X-Forwarded-Proto https
      - backend:
          serviceName: bar-web
          servicePort: '80'
          headerRule:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          - X-Forwarded-Proto https
```

**Pull request merged**
