### PR TITLE
Check HAProxy config before writing into configmap

### LINKED ISSUE #989: Test HAproxy config before setting to configmap

### PR DESCRIPTION
**Pull request by diptadas**
fixes #989

### CODE REVIEW

**Comment by jeffersongirao** [comment]
@diptadas @tamalsaha I think these changes will require also shuffling ordering to haproxy templates. Ex.: 

at https://github.com/appscode/voyager/blob/5191b1e1259783c0518b36e2af760fbe5870c519/hack/docker/voyager/templates/http-frontend.cfg#L47 

We do a redirect and after that we might render http-request. 

The above will trigger an validation error: `` "a 'http-request' rule placed after a 'redirect' rule will still be processed before." ``

**Comment by tamalsaha** [comment]
Thanks @jeffersongirao . I remember seeing this types of message but HAProxy does run. So, question is if that is an error or warning.

@diptadas , can you check?

**Comment by jeffersongirao** [comment]
@tamalsaha It seems to be a warning from the validator but I think we are taking it as an error, probably a non-zero exit code from the validator perspective. I'm getting these kind of logs:

``[ALERT] 128/093059 (74) : Fatal errors found in configuration.
I0509 09:30:59.212769       1 worker.go:80] Error syncing key my_ingress: invalid haproxy configuration, reason: exit status 1, output: [WARNING] 128/093059 (74) : parsing [/tmp/haproxy-config-046196133:51] : a 'http-request' rule placed after a 'redirect' rule will still be processed before.``

**Comment by tamalsaha** [comment]
Yeah, we need to fix this before pushing 7.0.0-rc.0 :(

**Comment by tamalsaha** [comment]
haproxy-cfg-check

@jeffersongirao , it seems that if there are only `[WARNING]`, the exit code for `haproxy -c -f ` is `0`. So, if the exit code is non-zero, then there is some fatal error in the generated config.

**Comment by jeffersongirao** [comment]
@tamalsaha you are right, I had another issue as well other than that. Wondering if we could report each individual line on the validation (being warning or error) as an event to the affected ingress. I think that would make it easier to know when and what is wrong. I can try to get a PR on that over the weekend. Wdyt?

**Comment by tamalsaha** [comment]
Current code will write a single event with the output from HAProxy process. It seems that actual errors are prefixed with `[ALERT]` on each line (see above image). So, if `err != nil`, you could potentially log the full output and then only include the `[ALERT]` lines in event (return as error). I am afraid that if we write multiple events for each `[ALERT]` line, it will be confusing . But I am open to try and see what works best. PRs are welcome ! I am going to try to cut `7.0.0-rc.0` this week. But we can include that in a follow up release soon after.

**Comment by tamalsaha** [comment]
So, we have to revert this change. This breaks for any Ingress that uses SSL cert. Example:
```
I0511 07:30:54.650692       1 ingress_crds.go:95] Sync/Add/Update for engress monitoring/haproxy-ingress
I0511 07:30:54.650748       1 parser.go:29] [a09aa2d5-234d-4f9b-9ef6-527c7d038015] [getting endpoints for  monitoring grafana port {1 0 3000}]
I0511 07:30:54.650766       1 parser.go:42] [a09aa2d5-234d-4f9b-9ef6-527c7d038015] [looking for services in namespace monitoring with name grafana]
I0511 07:30:54.654267       1 parser.go:124] [a09aa2d5-234d-4f9b-9ef6-527c7d038015] Found target port 3000 for service grafana
W0511 07:30:54.662273       1 parser.go:726] [a09aa2d5-234d-4f9b-9ef6-527c7d038015] haproxy.cfg is invalid for Ingress monitoring/haproxy-ingress:
invalid haproxy configuration, reason: exit status 1, output: [ALERT] 130/073054 (809) : parsing [/tmp/haproxy-config-028563170:45] : 'bind *:443' : unable to load SSL certificate file '/etc/ssl/private/haproxy/tls/' file does not exist.
[ALERT] 130/073054 (809) : Error(s) found in configuration file : /tmp/haproxy-config-028563170
[ALERT] 130/073054 (809) : Fatal errors found in configuration.
E0511 07:30:54.662654       1 worker.go:76] Failed to process key monitoring/haproxy-ingress. Reason: invalid haproxy configuration, reason: exit status 1, output: [ALERT] 130/073054 (809) : parsing [/tmp/haproxy-config-028563170:45] : 'bind *:443' : unable to load SSL certificate file '/etc/ssl/private/haproxy/tls/' file does not exist.
[ALERT] 130/073054 (809) : Error(s) found in configuration file : /tmp/haproxy-config-028563170
[ALERT] 130/073054 (809) : Fatal errors found in configuration.
E0511 07:30:54.663127       1 worker.go:90] invalid haproxy configuration, reason: exit status 1, output: [ALERT] 130/073054 (809) : parsing [/tmp/haproxy-config-028563170:45] : 'bind *:443' : unable to load SSL certificate file '/etc/ssl/private/haproxy/tls/' file does not exist.
[ALERT] 130/073054 (809) : Error(s) found in configuration file : /tmp/haproxy-config-028563170
[ALERT] 130/073054 (809) : Fatal errors found in configuration.
I0511 07:30:54.663573       1 worker.go:91] Dropping key "monitoring/haproxy-ingress" out of the queue: invalid haproxy configuration, reason: exit status 1, output: [ALERT] 130/073054 (809) : parsing [/tmp/haproxy-config-028563170:45] : 'bind *:443' : unable to load SSL certificate file '/etc/ssl/private/haproxy/tls/' file does not exist.
[ALERT] 130/073054 (809) : Error(s) found in configuration file : /tmp/haproxy-config-028563170
[ALERT] 130/073054 (809) : Fatal errors found in configuration.
```

**Pull request merged**
