### PR TITLE
Support AWS cert manager

### LINKED ISSUE #188: Allow exposing port 443 on the LoadBalancer Service
Currently, when attempting to terminate SSL at the LoadBalancer within AWS, we're using the annotation below to use AWS Certificate Manager instead of ACME.

```
    ingress.appscode.com/annotations-service: '{"service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:..."}'
```

However, this requires the voyager Service to be exposed on port 443, not port 80 (i.e. `tcp-80`).

http://kubernetes-on-aws.readthedocs.io/en/latest/user-guide/tls-termination.html

Would be great if there was a simple way to set up http->https forwarding to the AWS ELB, as well.

### PR DESCRIPTION
**Pull request by TamalSaha**
Fixes #188

### CODE REVIEW

**Comment by TamalSaha** [comment]
@julianvmodesto , this pr will open port 443 on LB service and send traffic to port 80 on HAProxy if `service-annotations` has `"service.beta.kubernetes.io/aws-load-balancer-ssl-cert"` set.

**Comment by julianvmodesto** [comment]
Excellent! Is this in 1.5.6? I tried putting `imagePullPolicy: Always` just in case, but I can't seem to see this feature in action.

**Comment by TamalSaha** [comment]
Yes. Do you see the 443-> 80 in the ingress service? https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/aws-cert-manager.md

**Comment by TamalSaha** [comment]
Also, if you exec into the operator pod and run `/operator version` you should see when this binary was complied. It should be June 16.

**Comment by julianvmodesto** [comment]
Oops sorry, I forgot to delete the ingress after updating -- it works! :smiley: 

Two things:
- instead of either tcp-80 or tcp-443, could we enable/add tcp-443 in addition to tcp-80 to the Service to allow both http and https access?
- is there a way to revert this? manually edit the LoadBalancer Service and remove the annotation?

**Comment by TamalSaha** [comment]
>>> instead of either tcp-80 or tcp-443, could we enable/add tcp-443 in addition to tcp-80 to the Service to allow both http and https access?
Do you always want both ports to be open? Or that will be based on some config?

>>> is there a way to revert this? manually edit the LoadBalancer Service and remove the annotation?
If you remove the service annotation `service.beta.kubernetes.io/aws-load-balancer-ssl-cert`, the port will  revert back to 80-> 80.

**Comment by julianvmodesto** [comment]
Hmm, if it could be based on some config, that might be useful, but my use case is to have both open.

However, at some point I'd like to figure out how we could set up http -> https redirect with something like `redirect scheme https code 301 if !{ ssl_fc }` in the frontend (or backend?).

Will try out removing the `service.beta.kubernetes.io/aws-load-balancer-ssl-cert` annotation!

**Comment by TamalSaha** [comment]
> However, at some point I'd like to figure out how we could set up http -> https redirect with something like redirect scheme https code 301 if !{ ssl_fc } in the frontend (or backend?).

This is already possible with with the version in master. Basically, AWS ELB adds a `X-Forwarded-Proto` header. In your Ingress, you can add backend rule what will redirect to HTTPS endpoint if this header is missing. You have to do this for each backend for port 80.

See here:
 - https://aws.amazon.com/premiumsupport/knowledge-center/redirect-http-https-elb/
 - http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-proto
 - https://www.exratione.com/2014/10/managing-haproxy-configuration-when-your-server-may-or-may-not-be-behind-an-ssl-terminating-proxy/

**Pull request merged**
