### PR TITLE
Chart support for custom tolerations and affinity

### LINKED ISSUE #1181: Custom Tolerations and affinity
It would be nice if the main Chart supported these attributes so it would be easier to use in environment where the pod scheduling is carefully controlled.

### PR DESCRIPTION
**Pull request by octplane**
Fixes #1181

### CODE REVIEW

**Comment by tamalsaha** [comment]
Thanks @octplane !

**Comment by octplane** [comment]
My pleasure!

**Comment by octplane** [comment]
Would it be possible to do a minor release of the Chart with this fix or is this too much work for you? 

Thanks!

**Comment by tamalsaha** [comment]
I have cut 7.4.0 https://github.com/appscode/voyager/releases/tag/7.4.0

**Comment by octplane** [comment]
Thanks!

**Pull request merged**
